project: "gigachat"
seed: 42
device: "cuda"
exp_name: "Llama-3.2-1B-sft"
log_dir: ".../gigachat/checkpoints-logs/${exp_name}"
checkpoint: "checkpoint-304"

model:
    path: "meta-llama/Llama-3.2-3B"
    marking_path: "meta-llama/Llama-3.1-8B-Instruct"
    save_path: ".../checkpoints-logs/age_llama_3-2_3B/checkpoint-352500"
    use_flash_attn: true
    use_bfloat16: true
    equal_pad_eos_id: true
    max_length: 8192

dataset:
    name: "age_pred"
    train_path: ".../src/ptls-experiments/scenario_age_pred/data/train_trx_file.parquet"
    test_path: ".../ptls-experiments/scenario_age_pred/data/test_trx_file.parquet"
    mcc_desc: true
    debug: false
    presave: true

    col_id: "client_id"
    header_features: 
        - "scaled time"
        - "amount(rubles, scaled)"
        - "trx date"
        - "Merchant category codes"
    header_separator: "|"
    features:
        - "event_time"
        - "amount_rur"
        - "trans_date"
        - "small_group"
    feature_separator: ", "
    trx_separator: "\n"

    marked_dataset: true
    chat: true
    chat_messages:
        system: >
            You are a specialized AI assistant designed for text data transformation.
            Your task is to take a structured list of financial transactions and convert them into different text-based formats based on the user's request. 
            Ensure clarity, accuracy, and proper formatting while preserving all original data fields.
            You are capable of transforming data into formats including:
            - JSON
            - Markdown
            - HTML
            - Plain text tables
            Always ensure the output is well-structured and visually clear. 
            If the user specifies a custom format, follow the instructions closely. Ask for clarifications when the format is ambiguous.
        user: >
            I have a list of financial transactions in a structured tabular format.
            Please creatively transform this data into a HTML textual representation. 
            ### Requirements:
            - Paraphrase category names and transaction types while keeping the meaning clear.
            - Ensure the data remains understandable but presented differently.
            - Give in the end a little bit analysis about this user transactions.
            Generate the transformed output. In response write only trasformed transactions, analysis and nothing more! (Don't give a description of your actions)
    sampling:
        temperature: 0.6
        top_p: 0.9 
        max_tokens: 8192

    coles_embeddings_path: ".../src/ptls-experiments/scenario_rosbank/data/mles_embeddings.pickle"

args:
    report_to: "wandb"
    log_dir: "./logs"
    logging_strategy: "steps"
    logging_steps: 10
    save_strategy: "epoch"
    save_steps: 4

    bf16: true
    train_epochs: 12
    max_steps: 5
    train_batch_size: 1
    warmup_steps: 608
    learning_rate: 1e-5
    max_grad_norm: 1
    lr_scheduler_type: "cosine"
    weight_decay: 1e-6
    adam_beta2: 0.95
    adam_epsilon: 1e-5
    optim: "adamw_torch"

    do_eval: "no"
    eval_batch_size: 6

    gradient_accumulation_steps: 1

inference:
    from_layer_slice: 9
